
TARGET_BIN := mp_process
TARGET_LIB :=
TARGET_SO  := 

SOURCE_CC  := log/MessageLog.cc daemon.cc mp_process.cc
SOURCE_CPP :=
SOURCE_LIB := -lpthread

#include /home/zouwenchen/test/cpp/make/Makefile.make
include Makefile.make


