
TARGET_BIN := 
TARGET_LIB := libcjsonhelper.a
TARGET_SO  := 

SOURCE_C   := cJSON.c
SOURCE_CC  := 
SOURCE_CPP := CJsonObject.cpp
SOURCE_LIB := -lpthread

#include /home/zouwenchen/test/cpp/make/Makefile.make
include Makefile.make


